instagram/config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # resources :blogs
  root 'posts#index'
  resources :posts
  devise_for :users, controllers:{
    sessions: 'users/sessions'
    }

  get '/users/index' => 'users#index'
  #rake route???
  # resourece :posts #아래 주석하고 하면 내가 가진 경로들 다 볼 수 있음
  # # index
  # get '/posts' => 'posts#index'
  #
  # #Create
  # get '/posts/new' => 'posts#new'
  # post '/posts' => 'posts#create'
  #
  # #Read
  # get '/posts/:id' =>'posts#show'
  #
  # #Update
  # get '/posts/:id/edit' =>'posts#edit'
  # put '/posts/:id' =>'posts#update'
  #
  # #Delete
  # delete '/posts/:id' => 'posts#destroy'
end

instagram/app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :postimage, PostImageUploader
  #mount_uploader는 belongs_to처럼 정해져있는거
  belongs_to :user
  
end

instagram/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  #befor_action은 하나의 액션을 실행하기 전에 해당 메소드를 실행
  #only:안에 있는 거에서만 set_post를 실행하겠다.
  before_action :authenticate_user!, except: :index
  # before_action :is_owner?, only: [:edit, :update, :destroy]
  load_and_authorize_resource param_method: :post_params
  #skip_authorize_resource only: [:new, :index] 이것도 생략 해주는 애??
  #load_and_authorize_resource excpt: :edit, param_method: :post_params 이렇게하면 edit은 넘어감

  #이렇게 하면 각각에 authorize 해줄 필요 없음

  def index
    if params["post"].nil?
      @posts=Post.all.reverse
    else
      @posts=Post.where("title LIKE ?", "%#{params["post"]["q"]}%")
      #%붙여주면
    end
  end

  def new
  end

  def create
    # Post.create(post_params)
     current_user.posts.create(post_params)
     # current_user => User의 인스턴스
     # current_user.posts => Post의 인스턴스
    redirect_to '/'
    puts '*****************************'
    puts post_params
    puts '*****************************'
  end

  def show
    # @post=Post.find(params[:id])

    authorize! :read,@post
  end

  def edit
    authorize! :update, @post
    #@post(글)에 대한 update 권한이 있는지 확인
    # @post=Post.find(params[:id])
  end

  def update
    # post=Post.find(params[:id])
  # @post.update(title: params[:title], content: params[:content])
  authorize! :update, @post
  @post.update(post_params)
    redirect_to '/'
  end

  def destroy
    authorize! :destroy, @post
    # post=Post.find(params[:id])
    @post.destroy
    redirect_to '/'
  end

  private
#private 위에는 public이라서 url로 요청오면 그것을 받아서 view를 보여준다.
#private은 해당 컨트롤러(PostsController)에서만 사용 가능함.
#객체에서 private 속성을 가지면 클래스 내부에서만 접근이 가능했었고, 이외의 상속 받은 클래스나 객체 인스턴스에서도 접근이 불가능했음.

  def set_post
    @post=Post.find(params[:id])
  end

  #strong parameter
  #특정 파라미터의 특정 값만 쓸거야라고 해주는거
  #실제로 쓸 파라미터들만 가져오는? 화이트리스트?
  def post_params
    params.require(:post).permit(:title,:content,:postimage,:q)
  end

  def is_owner?#?없어도 됨
    #게시글의 주인, 로그인한 사람이 같지 않으면
    redirect_to '/' and return unless @post.user_id==current_user.id
    #unless가 같지 않으면 참이니깐 같지 않으면 redirect_to '/'
    #unless => if @post.user_id != current_user.id
    #redirect_to '/'

  end

end

instagram/app/helpers/posts_helper.rb
module PostsHelper
end

instagram/app/views/posts/edit.html.erb
<!-- <form  action="/posts/<%=@post.id%>" method="post">
  <!- <!-  PUT할 때 꼮 POST로 써줘야함 ->
  <div class="form-group">
    <label for="exampleFormControlInput1">Title</label>
    <input type="text" class="form-control"  value="<%=@post.title%>" name="title">
    <label for="exampleFormControlInput1">Username</label>
    <input type="text" class="form-control"  value="<%=@post.username%>" name="username" disabled>
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">Textarea</label>
    <textarea class="form-control" rows="3" name="content"><%=@post.content%></textarea>
  </div>
  <input type="hidden" name="authenticity_token"  value="<%= form_authenticity_token %>"/><br />
  <input type="hidden" name="_method"  value="put"/><br />
  <a href="/"><button type="button" class="btn btn-info">Home</button></a>
  <!- <input type="submit" value="edit"> ->
</form> -->


<%= form_tag("/posts/#{@post.id}", method: "put", multipart: true) do %>
  <%=text_field_tag("post[title]",@post.title)%><br />
    <%=text_field_tag("post[username]",@post.username)%><br />
  <%=text_area_tag("post[content]",@post.content)%><br />
  <%= file_field_tag("post[postimage]")%><br />
  <%=submit_tag%>
<%end%>
<!--  form_tag는 값을 nil로 안넘겨줘서 사진 파일 안건들면 우너래 값으로 해줌 -->

instagram/app/views/posts/index.html.erb
<!-- <!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Instagramaroro</title>
  </head>
  <body>
    <h1>HI Instagramaroro</h1>
    <table class="table">
      <tr align="center">
        <th>Title</th>
        <th>Username</th>
        <th>Content</th>
        <th>img</th>
        <th colspan = "3" >Action</th>
      </tr>

    <% @posts.in_groups_of(3,false).each do |group|%>
    <div class = "row mt-3">
      <%group.each do |p|%>
    <tr>
     <td><%=p.title%></td>
     <td><%=p.username%></td>
     <td> <%=p.content%> </td>
     <div class = "col-4">
     <td><img src="<%=p.postimage%>" class = "img-fluid"></td>
     </div>
   <td><a href="/posts/<%=p.id%>"><button type="button" class="btn btn-info">show</button></a></td>
     <td><a href="/posts/<%=p.id%>/edit"><button type="button" class="btn btn-info">Edit</button></a></td>
     <td><a href="/posts/<%=p.id%>" data-method="delete" data-confirm="Are you sure?"><button type="button" class="btn btn-info">Delete</button></a></td>
   </tr>
    <%end%>
  </div>
    <%end%>
  </table>
    <a href="/posts/new"><button type="button" class="btn btn-info">new</button></a>
  </body>
</html> -->

<!-- current_user: <%#current_user.email%> -->
<br /><br />


<%= link_to "새글쓰기", new_post_path %>

<% @posts.in_groups_of(3, false).each do |group| %>
  <div class="row mt-3">
  <% group.each do |post| %>
    <div class="col-6 col-md-4">
      <a href="/posts/<%=post.id%>">
        <img src="<%=post.postimage.thumb%>" class="img-fluid rounded">

      </a><br />
        <span class ="font-weight-bold text-nowrap">Title: </span> <%=post.title%>  /
        <span class ="font-weight-bold text-nowrap"> Username: </span> <%=post.user.username%>  /
             <span class ="font-weight-bold text-nowrap">Content: </span><%=post.content%>
    </div>

  <% end %>
  </div>
<% end %>

instagram/app/views/posts/new.html.erb
<!-- <form action = "/posts" method="post">
  <div class="form-group">
    <label for="exampleFormControlInput1">Title</label>
    <input type="text" class="form-control"  placeholder="Title" name="title">
    <label for="exampleFormControlInput1">Username</label>
    <input type="text" class="form-control"  placeholder="Username" name="username">
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">Textarea</label>
    <textarea class="form-control" rows="3" name="content"></textarea>
  </div>
  <input type="hidden" name="authenticity_token"  value="<%= form_authenticity_token %>"/><br />
  <input type="submit" name="submit" value="submit">
</form> -->


<%= form_tag("/posts", method: "post", multipart: true) do %>
  <!-- <% text_field_tag("post[title]")%> <hr />
  <%= text_area_tag("post[content]") %> <hr />
  <%= file_field_tag("post[postimage]") %><hr />
  <!- 글 이외에 이미지나 파일들 받으려면 multipart: true 해줘야함->
  <%= submit_tag %> -->

  <div class ="form-group">
    <%=label_tag(:post_title, "title")%>
    <%= text_field_tag("post[title]","",class: "form-control")%> <hr />
  </div>
  <div class ="form-group">
    <%=label_tag(:post_username, "username")%>
    <!-- <%= text_field_tag("post[username]","#{current_user.username}",class: "form-control")%> <hr /> -->
      
  </div>
  <div class ="form-group">
    <%=label_tag(:post_content, "content")%>
    <%= text_area_tag("post[content]","",class: "form-control") %> <hr />
  </div>
  <div class ="form-group">
    <%=label_tag(:post_postimage, "attachedfile")%>
    <%= file_field_tag("post[postimage]", class: "form-control")%><hr />
    <!-- <%= submit_tag %> -->
    <%=button_tag("submit",class:"btn btn-info")%>
  </div>

<% end %>

instagram/app/views/posts/read.html.erb
<form action="/posts/<%=@post.id%>/edit">
    <div class="d-flex justify-content-center">
      <figure class = "figure">
        <img src="<%=@post.postimage%>" class="figure-img img-fluid rounded" alt="A generic square placeholder image with rounded corners in a figure." style="height: 70vh;">
        <figcaption class="figure-caption text-right">A caption for the above image.</figcaption>
      </figure>
    </div>
  <div class="form-group">
    <label for="exampleFormControlInput1">Title</label>
    <input type="text" class="form-control"  value="<%=@post.title%>" name="title" disabled>
    <label for="exampleFormControlInput1">Username</label>
    <input type="text" class="form-control"  value="<%=@post.username%>" name="username" disabled>
  </div>

  <div class="form-group">
    <label for="exampleFormControlTextarea1">Textarea</label>
    <textarea class="form-control" rows="3" name="content" disabled><%=@post.content%></textarea>
<br />


  </div>

    <a href="/"><button type="button" class="btn btn-info">Home</button></a>
    <input class="btn btn-info" type="submit" value="edit">
     <a href="/posts/<%=@post.id%>" data-confirm="Are you sure?" data-method="delete"><button type="button" class="btn btn-info">Delete</button></a>

</form>

instagram/app/views/posts/show.html.erb
<form action="/posts/<%=@post.id%>/edit">
    <div class="d-flex justify-content-center">
      <figure class = "figure">
        <img src="<%=@post.postimage%>" class="figure-img img-fluid rounded" alt="A generic square placeholder image with rounded corners in a figure." style="height: 70vh;">
        <figcaption class="figure-caption text-right">A caption for the above image.</figcaption>
      </figure>
    </div>
  <div class="form-group">
    <label for="exampleFormControlInput1">Title</label>
    <input type="text" class="form-control"  value="<%=@post.title%>" name="title" disabled>
    <label for="exampleFormControlInput1">Username</label>
    <input type="text" class="form-control"  value="<%=@post.user.username%>" name="current_user.username" disabled>
  </div>

  <div class="form-group">
    <label for="exampleFormControlTextarea1">Textarea</label>
    <textarea class="form-control" rows="3" name="content" disabled><%=@post.content%></textarea>
<br />


  </div>

    <a href="/"><button type="button" class="btn btn-info">Home</button></a>

     <% if can? :update, @post %>
         <input class="btn btn-info" type="submit" value="edit">
        <!-- <p><a href="/posts/<%=@post.id%>/edit">수정</a></p> -->
      <% end %>
      <% if can? :destroy, @post %>
        <a href="/posts/<%=@post.id%>" data-confirm="Are you sure?" data-method="delete"><button type="button" class="btn btn-info">Delete</button></a>
        <!-- <p><a href="/posts/<%=@post.id%>" data-method="delete" data-confirm="삭제할래?">삭제</a></p> -->
    <% end %>
</form>